### ISSUE TITLE
有计划更新Lvgl到最新的版本吗？

### ISSUE THREAD

**Issue by orange2348** [liu2guang/LittlevGL2RTT#12]
目前LVGL最新的版本已经到7.2.0，有计划更新到最新的版本吗？

**Comment by shuzheforandroid** [comment]
有个屁,RT在推柿饼UI,这个无限搁置,直接阉割touch

**Comment by liu2guang** [comment]
emmm，sorry
这个主要是我太懒了，有计划但是没有时间去弄，最近比较忙。
如果有需要可以提pr，这个我会第一时间看的。。

**Comment by shuzheforandroid** [comment]
> emmm，sorry
> 这个主要是我太懒了，有计划但是没有时间去弄，最近比较忙。
> 如果有需要可以提pr，这个我会第一时间看的。。

RT群里 我起码遇到7 8个用了大佬你的RT市场的LVGL 没tuoch事件 又自己苦逼的去移植的
开源也是一份责任啊 大佬等你更新
