### ISSUE TITLE
一直卡在初始化默认样式这里lv_theme_t * th = LV_THEME_DEFAULT_INIT

### ISSUE THREAD

**Issue by hu-lu** [liu2guang/LittlevGL2RTT#15]
您好，感谢更新lvgl到v7.7。
我按照步骤在menuconfig中添加littlevgl2RTT包，keil5编译工程没有问题，下载运行Demo时程序卡住，经过排查，发现问题是在
`    lv_theme_t * th = LV_THEME_DEFAULT_INIT(LV_THEME_DEFAULT_COLOR_PRIMARY, LV_THEME_DEFAULT_COLOR_SECONDARY,
                                            LV_THEME_DEFAULT_FLAG,
                                            LV_THEME_DEFAULT_FONT_SMALL, LV_THEME_DEFAULT_FONT_NORMAL, LV_THEME_DEFAULT_FONT_SUBTITLE, LV_THEME_DEFAULT_FONT_TITLE);
    lv_theme_set_act(th);

rt_kprintf("test");   // 当注释掉上面两条语句后，终端能够打印出test ，否则不能打印，因此怀疑是初始化默认样式的问题。`

本人水平不高，不知怎样解决，希望作者百忙之中抽空指点一下迷津^_^!

**Comment by mysterywolf** [comment]
现在这个包由 @heyuanjie87 维护，可以向他提问

**Comment by hu-lu** [comment]
好的好的，谢谢

**Comment by heyuanjie87** [comment]
先单步跟踪下具体卡在哪，当时我在k210上测试的，可以看到显示msgbox等就没测更多板子，如果你实在无法解决可以借给我板子调一下
