### ISSUE TITLE
Blog post on LittelvGL's blog

### ISSUE THREAD

**Issue by kisvegabor** [liu2guang/LittlevGL2RTT#7]
Hi,

Would you be interested in writing a post about this project on [LittelvGL's blog](https://blog.littlevgl.com/)?

A short introduction of RTT and a getting started guide with it and LitteveGL would be very welcome!

If you are interested, please have a look at https://blog.littlevgl.com/2018-12-06/contributing#writing-a-blog-post-about-your-experiences

**Comment by liu2guang** [comment]
Yes I do, I'm very glad to make the offer~~

**Comment by kisvegabor** [comment]
Awesome! I'm curiously waiting for it!

**Comment by kisvegabor** [comment]
Hi,

Could you make any progress with the post?
